### ISSUE TITLE
spawn-protectionがでかすぎた

### ISSUE THREAD

**Issue by KisaragiEffective** [ksrgtech/minecraft-mod#3]
`spawn-protection=100`としたため。各ディメンション (かどうかはわからないが、少なくともネザーは影響下) にspawn-protectionがかかるのでプレイ時の大きな妨げになることが考えられる。

**Comment by KisaragiEffective** [comment]
なんでdimensionごとのspawn-protectionを設定する方法がないの？？？

**Comment by nabr2730** [comment]
forgeにspigotプラグイン使えるのを使ってworldGuard使うしかなさそう？

**Comment by KisaragiEffective** [comment]
とりあえず32にしてデカすぎるって声がなさそうなので良さそう。ネザー？~~知らない子ですね~~:cross: 運用でカバー :cross:
